run:
  timeout: 10m

linters:
  disable-all: true
  enable:
    - gofumpt
    - goimports
    - unused       # уже ловит неиспользуемые поля
    - govet
    - errcheck
    # - lll
    - staticcheck
    - ineffassign
    - gosimple
    - misspell
    - gocritic

linters-settings:
  lll:
    line-length: 120
    tab-width: 4
    ignore-comments: true
    allow-non-ascii: true

  gocritic:
    enabled-checks: []
