run:
  timeout: 10m

linters:
  disable-all: true
  enable:
    - gofumpt
    - goimports
    - unused
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - gosimple
    - misspell
    - gocritic

linters-settings:
  gofmt:
    rewrite-rules:
      - pattern: 'interface{}'
        replacement: 'any'

  gocritic:
    enabled-checks: []

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck