// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/service.go

// Package servmocks is a generated GoMock package.
package servmocks

import (
	entity "app/internal/entity"
	servdto "app/internal/service/dto"
	context "context"
	reflect "reflect"

	trm "github.com/avito-tech/go-transaction-manager/trm/v2"
	gomock "github.com/golang/mock/gomock"
)

// MockTRManager is a mock of TRManager interface.
type MockTRManager struct {
	ctrl     *gomock.Controller
	recorder *MockTRManagerMockRecorder
}

// MockTRManagerMockRecorder is the mock recorder for MockTRManager.
type MockTRManagerMockRecorder struct {
	mock *MockTRManager
}

// NewMockTRManager creates a new mock instance.
func NewMockTRManager(ctrl *gomock.Controller) *MockTRManager {
	mock := &MockTRManager{ctrl: ctrl}
	mock.recorder = &MockTRManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTRManager) EXPECT() *MockTRManagerMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockTRManager) Do(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Do indicates an expected call of Do.
func (mr *MockTRManagerMockRecorder) Do(ctx, fn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockTRManager)(nil).Do), ctx, fn)
}

// DoWithSettings mocks base method.
func (m *MockTRManager) DoWithSettings(ctx context.Context, s trm.Settings, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoWithSettings", ctx, s, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// DoWithSettings indicates an expected call of DoWithSettings.
func (mr *MockTRManagerMockRecorder) DoWithSettings(ctx, s, fn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoWithSettings", reflect.TypeOf((*MockTRManager)(nil).DoWithSettings), ctx, s, fn)
}

// MockTeams is a mock of Teams interface.
type MockTeams struct {
	ctrl     *gomock.Controller
	recorder *MockTeamsMockRecorder
}

// MockTeamsMockRecorder is the mock recorder for MockTeams.
type MockTeamsMockRecorder struct {
	mock *MockTeams
}

// NewMockTeams creates a new mock instance.
func NewMockTeams(ctrl *gomock.Controller) *MockTeams {
	mock := &MockTeams{ctrl: ctrl}
	mock.recorder = &MockTeamsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeams) EXPECT() *MockTeamsMockRecorder {
	return m.recorder
}

// CreateOrUpdateTeam mocks base method.
func (m *MockTeams) CreateOrUpdateTeam(ctx context.Context, in servdto.CrOrUpTeamInput) (entity.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdateTeam", ctx, in)
	ret0, _ := ret[0].(entity.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrUpdateTeam indicates an expected call of CreateOrUpdateTeam.
func (mr *MockTeamsMockRecorder) CreateOrUpdateTeam(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateTeam", reflect.TypeOf((*MockTeams)(nil).CreateOrUpdateTeam), ctx, in)
}

// GetTeam mocks base method.
func (m *MockTeams) GetTeam(ctx context.Context, teamName string) (entity.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeam", ctx, teamName)
	ret0, _ := ret[0].(entity.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeam indicates an expected call of GetTeam.
func (mr *MockTeamsMockRecorder) GetTeam(ctx, teamName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeam", reflect.TypeOf((*MockTeams)(nil).GetTeam), ctx, teamName)
}

// ReplaceTeamMembers mocks base method.
func (m *MockTeams) ReplaceTeamMembers(ctx context.Context, in servdto.ReplaceMembersInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceTeamMembers", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceTeamMembers indicates an expected call of ReplaceTeamMembers.
func (mr *MockTeamsMockRecorder) ReplaceTeamMembers(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceTeamMembers", reflect.TypeOf((*MockTeams)(nil).ReplaceTeamMembers), ctx, in)
}

// MockUsers is a mock of Users interface.
type MockUsers struct {
	ctrl     *gomock.Controller
	recorder *MockUsersMockRecorder
}

// MockUsersMockRecorder is the mock recorder for MockUsers.
type MockUsersMockRecorder struct {
	mock *MockUsers
}

// NewMockUsers creates a new mock instance.
func NewMockUsers(ctrl *gomock.Controller) *MockUsers {
	mock := &MockUsers{ctrl: ctrl}
	mock.recorder = &MockUsersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsers) EXPECT() *MockUsersMockRecorder {
	return m.recorder
}

// SetIsActive mocks base method.
func (m *MockUsers) SetIsActive(ctx context.Context, in servdto.SetIsActiveInput) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetIsActive", ctx, in)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetIsActive indicates an expected call of SetIsActive.
func (mr *MockUsersMockRecorder) SetIsActive(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetIsActive", reflect.TypeOf((*MockUsers)(nil).SetIsActive), ctx, in)
}

// MockPullReq is a mock of PullReq interface.
type MockPullReq struct {
	ctrl     *gomock.Controller
	recorder *MockPullReqMockRecorder
}

// MockPullReqMockRecorder is the mock recorder for MockPullReq.
type MockPullReqMockRecorder struct {
	mock *MockPullReq
}

// NewMockPullReq creates a new mock instance.
func NewMockPullReq(ctrl *gomock.Controller) *MockPullReq {
	mock := &MockPullReq{ctrl: ctrl}
	mock.recorder = &MockPullReqMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPullReq) EXPECT() *MockPullReqMockRecorder {
	return m.recorder
}

// AssignReviewers mocks base method.
func (m *MockPullReq) AssignReviewers(ctx context.Context, in servdto.AssignReviewersInput) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignReviewers", ctx, in)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssignReviewers indicates an expected call of AssignReviewers.
func (mr *MockPullReqMockRecorder) AssignReviewers(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignReviewers", reflect.TypeOf((*MockPullReq)(nil).AssignReviewers), ctx, in)
}

// CreatePR mocks base method.
func (m *MockPullReq) CreatePR(ctx context.Context, in servdto.CreatePRInput) (entity.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePR", ctx, in)
	ret0, _ := ret[0].(entity.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePR indicates an expected call of CreatePR.
func (mr *MockPullReqMockRecorder) CreatePR(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePR", reflect.TypeOf((*MockPullReq)(nil).CreatePR), ctx, in)
}

// GetPR mocks base method.
func (m *MockPullReq) GetPR(ctx context.Context, prID string) (entity.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPR", ctx, prID)
	ret0, _ := ret[0].(entity.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPR indicates an expected call of GetPR.
func (mr *MockPullReqMockRecorder) GetPR(ctx, prID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPR", reflect.TypeOf((*MockPullReq)(nil).GetPR), ctx, prID)
}

// GetPRsByReviewer mocks base method.
func (m *MockPullReq) GetPRsByReviewer(ctx context.Context, uID string) ([]entity.PullRequestShort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPRsByReviewer", ctx, uID)
	ret0, _ := ret[0].([]entity.PullRequestShort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPRsByReviewer indicates an expected call of GetPRsByReviewer.
func (mr *MockPullReqMockRecorder) GetPRsByReviewer(ctx, uID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPRsByReviewer", reflect.TypeOf((*MockPullReq)(nil).GetPRsByReviewer), ctx, uID)
}

// MergePR mocks base method.
func (m *MockPullReq) MergePR(ctx context.Context, prID string) (entity.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergePR", ctx, prID)
	ret0, _ := ret[0].(entity.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MergePR indicates an expected call of MergePR.
func (mr *MockPullReqMockRecorder) MergePR(ctx, prID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergePR", reflect.TypeOf((*MockPullReq)(nil).MergePR), ctx, prID)
}

// ReassignReviewer mocks base method.
func (m *MockPullReq) ReassignReviewer(ctx context.Context, in servdto.ReassignReviewerInput) (servdto.ReassignReviewerOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReassignReviewer", ctx, in)
	ret0, _ := ret[0].(servdto.ReassignReviewerOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReassignReviewer indicates an expected call of ReassignReviewer.
func (mr *MockPullReqMockRecorder) ReassignReviewer(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReassignReviewer", reflect.TypeOf((*MockPullReq)(nil).ReassignReviewer), ctx, in)
}

// MockAuth is a mock of Auth interface.
type MockAuth struct {
	ctrl     *gomock.Controller
	recorder *MockAuthMockRecorder
}

// MockAuthMockRecorder is the mock recorder for MockAuth.
type MockAuthMockRecorder struct {
	mock *MockAuth
}

// NewMockAuth creates a new mock instance.
func NewMockAuth(ctrl *gomock.Controller) *MockAuth {
	mock := &MockAuth{ctrl: ctrl}
	mock.recorder = &MockAuthMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuth) EXPECT() *MockAuthMockRecorder {
	return m.recorder
}

// GenerateToken mocks base method.
func (m *MockAuth) GenerateToken(ctx context.Context, in servdto.GenTokenInput) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToken", ctx, in)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateToken indicates an expected call of GenerateToken.
func (mr *MockAuthMockRecorder) GenerateToken(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToken", reflect.TypeOf((*MockAuth)(nil).GenerateToken), ctx, in)
}

// ParseToken mocks base method.
func (m *MockAuth) ParseToken(accessToken string) (entity.ParsedToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseToken", accessToken)
	ret0, _ := ret[0].(entity.ParsedToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseToken indicates an expected call of ParseToken.
func (mr *MockAuthMockRecorder) ParseToken(accessToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseToken", reflect.TypeOf((*MockAuth)(nil).ParseToken), accessToken)
}

// MockStats is a mock of Stats interface.
type MockStats struct {
	ctrl     *gomock.Controller
	recorder *MockStatsMockRecorder
}

// MockStatsMockRecorder is the mock recorder for MockStats.
type MockStatsMockRecorder struct {
	mock *MockStats
}

// NewMockStats creates a new mock instance.
func NewMockStats(ctrl *gomock.Controller) *MockStats {
	mock := &MockStats{ctrl: ctrl}
	mock.recorder = &MockStatsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStats) EXPECT() *MockStatsMockRecorder {
	return m.recorder
}

// GetStats mocks base method.
func (m *MockStats) GetStats(ctx context.Context) (servdto.GetStatsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx)
	ret0, _ := ret[0].(servdto.GetStatsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockStatsMockRecorder) GetStats(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockStats)(nil).GetStats), ctx)
}
