// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repo/repo.go

// Package repomocks is a generated GoMock package.
package repomocks

import (
	entity "app/internal/entity"
	repodto "app/internal/repo/dto"
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockTeams is a mock of Teams interface.
type MockTeams struct {
	ctrl     *gomock.Controller
	recorder *MockTeamsMockRecorder
}

// MockTeamsMockRecorder is the mock recorder for MockTeams.
type MockTeamsMockRecorder struct {
	mock *MockTeams
}

// NewMockTeams creates a new mock instance.
func NewMockTeams(ctrl *gomock.Controller) *MockTeams {
	mock := &MockTeams{ctrl: ctrl}
	mock.recorder = &MockTeamsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeams) EXPECT() *MockTeamsMockRecorder {
	return m.recorder
}

// CreateTeam mocks base method.
func (m *MockTeams) CreateTeam(ctx context.Context, teamName string) (entity.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTeam", ctx, teamName)
	ret0, _ := ret[0].(entity.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTeam indicates an expected call of CreateTeam.
func (mr *MockTeamsMockRecorder) CreateTeam(ctx, teamName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTeam", reflect.TypeOf((*MockTeams)(nil).CreateTeam), ctx, teamName)
}

// DeactivateTeamUsers mocks base method.
func (m *MockTeams) DeactivateTeamUsers(ctx context.Context, teamName string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateTeamUsers", ctx, teamName)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeactivateTeamUsers indicates an expected call of DeactivateTeamUsers.
func (mr *MockTeamsMockRecorder) DeactivateTeamUsers(ctx, teamName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateTeamUsers", reflect.TypeOf((*MockTeams)(nil).DeactivateTeamUsers), ctx, teamName)
}

// DeleteUsersFromTeam mocks base method.
func (m *MockTeams) DeleteUsersFromTeam(ctx context.Context, teamName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUsersFromTeam", ctx, teamName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUsersFromTeam indicates an expected call of DeleteUsersFromTeam.
func (mr *MockTeamsMockRecorder) DeleteUsersFromTeam(ctx, teamName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUsersFromTeam", reflect.TypeOf((*MockTeams)(nil).DeleteUsersFromTeam), ctx, teamName)
}

// GetTeam mocks base method.
func (m *MockTeams) GetTeam(ctx context.Context, teamName string) (entity.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeam", ctx, teamName)
	ret0, _ := ret[0].(entity.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeam indicates an expected call of GetTeam.
func (mr *MockTeamsMockRecorder) GetTeam(ctx, teamName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeam", reflect.TypeOf((*MockTeams)(nil).GetTeam), ctx, teamName)
}

// MockUsers is a mock of Users interface.
type MockUsers struct {
	ctrl     *gomock.Controller
	recorder *MockUsersMockRecorder
}

// MockUsersMockRecorder is the mock recorder for MockUsers.
type MockUsersMockRecorder struct {
	mock *MockUsers
}

// NewMockUsers creates a new mock instance.
func NewMockUsers(ctrl *gomock.Controller) *MockUsers {
	mock := &MockUsers{ctrl: ctrl}
	mock.recorder = &MockUsersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsers) EXPECT() *MockUsersMockRecorder {
	return m.recorder
}

// DeleteUsersByTeam mocks base method.
func (m *MockUsers) DeleteUsersByTeam(ctx context.Context, teamName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUsersByTeam", ctx, teamName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUsersByTeam indicates an expected call of DeleteUsersByTeam.
func (mr *MockUsersMockRecorder) DeleteUsersByTeam(ctx, teamName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUsersByTeam", reflect.TypeOf((*MockUsers)(nil).DeleteUsersByTeam), ctx, teamName)
}

// GetActiveUsersTeam mocks base method.
func (m *MockUsers) GetActiveUsersTeam(ctx context.Context, teamName string, exIDs []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveUsersTeam", ctx, teamName, exIDs)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveUsersTeam indicates an expected call of GetActiveUsersTeam.
func (mr *MockUsersMockRecorder) GetActiveUsersTeam(ctx, teamName, exIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveUsersTeam", reflect.TypeOf((*MockUsers)(nil).GetActiveUsersTeam), ctx, teamName, exIDs)
}

// GetUserByID mocks base method.
func (m *MockUsers) GetUserByID(ctx context.Context, userID string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, userID)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUsersMockRecorder) GetUserByID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUsers)(nil).GetUserByID), ctx, userID)
}

// SetIsActive mocks base method.
func (m *MockUsers) SetIsActive(ctx context.Context, userID string, isActive *bool) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetIsActive", ctx, userID, isActive)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetIsActive indicates an expected call of SetIsActive.
func (mr *MockUsersMockRecorder) SetIsActive(ctx, userID, isActive interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetIsActive", reflect.TypeOf((*MockUsers)(nil).SetIsActive), ctx, userID, isActive)
}

// UpsetBulk mocks base method.
func (m *MockUsers) UpsetBulk(ctx context.Context, user []entity.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsetBulk", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsetBulk indicates an expected call of UpsetBulk.
func (mr *MockUsersMockRecorder) UpsetBulk(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsetBulk", reflect.TypeOf((*MockUsers)(nil).UpsetBulk), ctx, user)
}

// MockPullReq is a mock of PullReq interface.
type MockPullReq struct {
	ctrl     *gomock.Controller
	recorder *MockPullReqMockRecorder
}

// MockPullReqMockRecorder is the mock recorder for MockPullReq.
type MockPullReqMockRecorder struct {
	mock *MockPullReq
}

// NewMockPullReq creates a new mock instance.
func NewMockPullReq(ctrl *gomock.Controller) *MockPullReq {
	mock := &MockPullReq{ctrl: ctrl}
	mock.recorder = &MockPullReqMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPullReq) EXPECT() *MockPullReqMockRecorder {
	return m.recorder
}

// AssignReviewers mocks base method.
func (m *MockPullReq) AssignReviewers(ctx context.Context, prID string, reviewers []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignReviewers", ctx, prID, reviewers)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssignReviewers indicates an expected call of AssignReviewers.
func (mr *MockPullReqMockRecorder) AssignReviewers(ctx, prID, reviewers interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignReviewers", reflect.TypeOf((*MockPullReq)(nil).AssignReviewers), ctx, prID, reviewers)
}

// ChangeReviewer mocks base method.
func (m *MockPullReq) ChangeReviewer(ctx context.Context, in repodto.ChangeReviewerInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeReviewer", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeReviewer indicates an expected call of ChangeReviewer.
func (mr *MockPullReqMockRecorder) ChangeReviewer(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeReviewer", reflect.TypeOf((*MockPullReq)(nil).ChangeReviewer), ctx, in)
}

// CreatePR mocks base method.
func (m *MockPullReq) CreatePR(ctx context.Context, in repodto.CreatePRInput) (entity.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePR", ctx, in)
	ret0, _ := ret[0].(entity.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePR indicates an expected call of CreatePR.
func (mr *MockPullReqMockRecorder) CreatePR(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePR", reflect.TypeOf((*MockPullReq)(nil).CreatePR), ctx, in)
}

// DeleteReviewer mocks base method.
func (m *MockPullReq) DeleteReviewer(ctx context.Context, uID, prID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteReviewer", ctx, uID, prID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteReviewer indicates an expected call of DeleteReviewer.
func (mr *MockPullReqMockRecorder) DeleteReviewer(ctx, uID, prID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteReviewer", reflect.TypeOf((*MockPullReq)(nil).DeleteReviewer), ctx, uID, prID)
}

// GetPR mocks base method.
func (m *MockPullReq) GetPR(ctx context.Context, prID string) (entity.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPR", ctx, prID)
	ret0, _ := ret[0].(entity.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPR indicates an expected call of GetPR.
func (mr *MockPullReqMockRecorder) GetPR(ctx, prID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPR", reflect.TypeOf((*MockPullReq)(nil).GetPR), ctx, prID)
}

// GetPRsByReviewer mocks base method.
func (m *MockPullReq) GetPRsByReviewer(ctx context.Context, uID string) ([]entity.PullRequestShort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPRsByReviewer", ctx, uID)
	ret0, _ := ret[0].([]entity.PullRequestShort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPRsByReviewer indicates an expected call of GetPRsByReviewer.
func (mr *MockPullReqMockRecorder) GetPRsByReviewer(ctx, uID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPRsByReviewer", reflect.TypeOf((*MockPullReq)(nil).GetPRsByReviewer), ctx, uID)
}

// MergePR mocks base method.
func (m *MockPullReq) MergePR(ctx context.Context, prID string) (*time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergePR", ctx, prID)
	ret0, _ := ret[0].(*time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MergePR indicates an expected call of MergePR.
func (mr *MockPullReqMockRecorder) MergePR(ctx, prID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergePR", reflect.TypeOf((*MockPullReq)(nil).MergePR), ctx, prID)
}

// SetNeedMoreReviewers mocks base method.
func (m *MockPullReq) SetNeedMoreReviewers(ctx context.Context, prID string, value bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetNeedMoreReviewers", ctx, prID, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetNeedMoreReviewers indicates an expected call of SetNeedMoreReviewers.
func (mr *MockPullReqMockRecorder) SetNeedMoreReviewers(ctx, prID, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNeedMoreReviewers", reflect.TypeOf((*MockPullReq)(nil).SetNeedMoreReviewers), ctx, prID, value)
}

// MockStats is a mock of Stats interface.
type MockStats struct {
	ctrl     *gomock.Controller
	recorder *MockStatsMockRecorder
}

// MockStatsMockRecorder is the mock recorder for MockStats.
type MockStatsMockRecorder struct {
	mock *MockStats
}

// NewMockStats creates a new mock instance.
func NewMockStats(ctrl *gomock.Controller) *MockStats {
	mock := &MockStats{ctrl: ctrl}
	mock.recorder = &MockStatsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStats) EXPECT() *MockStatsMockRecorder {
	return m.recorder
}

// GetPRStats mocks base method.
func (m *MockStats) GetPRStats(ctx context.Context) ([]repodto.PRStatsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPRStats", ctx)
	ret0, _ := ret[0].([]repodto.PRStatsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPRStats indicates an expected call of GetPRStats.
func (mr *MockStatsMockRecorder) GetPRStats(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPRStats", reflect.TypeOf((*MockStats)(nil).GetPRStats), ctx)
}

// GetReviewerStats mocks base method.
func (m *MockStats) GetReviewerStats(ctx context.Context) ([]repodto.ReviewerStatsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReviewerStats", ctx)
	ret0, _ := ret[0].([]repodto.ReviewerStatsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReviewerStats indicates an expected call of GetReviewerStats.
func (mr *MockStatsMockRecorder) GetReviewerStats(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReviewerStats", reflect.TypeOf((*MockStats)(nil).GetReviewerStats), ctx)
}
